### PR TITLE
Added space for tx history visualization. Closes #23

### LINKED ISSUE #23: Add space for transaction history visualization

### PR DESCRIPTION
**Pull request by IanMacDougall**

### CODE REVIEW

**Review by hanson-lam — APPROVED** [review]
looks good

**Review by CarolineRinks — APPROVED** [review]

**Comment by IanMacDougall** [comment]
Do not merge until brush feature is fully implemented

**Comment by IanMacDougall** [comment]
@CarolineRinks @hanson-lam @dhuang0212 
I have finished the changes to the tx history visualization that enable dynamic view port resizing. The base tool has been implemented, and we can now start improving it next semester. Take a look at the changes at your earliest convenience

**Comment by IanMacDougall** [comment]
Closes #26

**Pull request merged**
